# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

cache:
  paths:
    - .m2/repository

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: |
       chmod +x  ./deployment/retailer1/rubix-install.sh
       ./deployment/retailer1/rubix-install.sh
      env:
        API_HOST: ${{ secrets.DEV_API_HOST }}
        DEV_ACCOUNT: ${{ vars.DEV_ACCOUNT }}
        GITHUB_TOKEN: ${{ github.token }}
